import React, {useState,useEffect} from 'react';
import {ArrowUpRight, ShoppingBag, Minus, Plus, ChevronDown} from 'lucide-react';
import {collections,products} from './data';
export default function LiveProduct({product:p,add,money,ProductCard}) {
 const initial=p.variants.find(v=>v.availableForSale)||p.variants[0];
 const [selected,setSelected]=useState(Object.fromEntries(initial.selectedOptions.map(o=>[o.name,o.value])));
 const [qty,setQty]=useState(1); const [view,setView]=useState(null);
 const variant=p.variants.find(v=>v.selectedOptions.every(o=>selected[o.name]===o.value));
 const image=view!==null?p.images[view]:variant?.image||p.images[0];
 const c=collections.find(c=>c.slug===p.collection);
 useEffect(()=>{document.title=`${p.name} — Lifted High Apparel`},[p.name]);
 return <main><div className="product-detail section-pad"><div><div className="detail-image">{image?<img className="real-product-image" src={image.url} alt={image.altText||p.name}/>:<div className="no-product-photo">Photo coming soon</div>}</div><div className="thumbnails">{p.images.map((im,i)=><button key={im.url} aria-label={`Show product image ${i+1}`} aria-pressed={image?.url===im.url} className={image?.url===im.url?'selected':''} onClick={()=>setView(i)}><img src={im.url} alt={im.altText||`${p.name}, image ${i+1}`}/></button>)}</div></div><div className="product-info"><a className="eyebrow" href={c?`/${c.slug}`:'/shop'}>{c?`${c.name} COLLECTION`:'EVERYDAY ESSENTIALS'} <ArrowUpRight size={14}/></a><h1>{p.name}</h1><div className="price">{money(variant?Number(variant.price.amount):p.price)}</div><p>{p.description}</p>{p.options.filter(o=>!(o.name==='Title'&&o.values.length===1&&o.values[0]==='Default Title')).map(o=><div key={o.name}><label className="option-label" htmlFor={`option-${o.name}`}>{o.name.toUpperCase()} — {selected[o.name]}</label><select id={`option-${o.name}`} value={selected[o.name]} onChange={e=>{setSelected(prev=>({...prev,[o.name]:e.target.value}));setView(null)}}>{o.values.map(value=><option key={value}>{value}</option>)}</select></div>)}<div className="add-row"><div className="quantity"><button aria-label="Decrease quantity" onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={16}/></button><span>{qty}</span><button aria-label="Increase quantity" onClick={()=>setQty(qty+1)}><Plus size={16}/></button></div><button className="button dark" disabled={!variant?.availableForSale} onClick={()=>add(p,selected.Size||'One size',selected.Color||selected.Colour||variant.title,qty,variant)}>{variant?.availableForSale?'ADD TO BAG':variant?'SOLD OUT':'UNAVAILABLE COMBINATION'}<ShoppingBag size={18}/></button></div><details><summary>Shipping & returns <ChevronDown size={17}/></summary><p>Shipping rates and taxes are calculated at checkout. Review the store’s shipping and return policies at Shopify checkout before placing your order.</p></details></div></div><section className="section-pad related"><div className="section-heading"><h2>Good company.</h2><a className="underlined-link" href="/shop">Shop all <ArrowUpRight size={16}/></a></div><div className="product-grid">{products.filter(q=>q.id!==p.id).slice(0,4).map(q=><ProductCard p={q} key={q.id}/>)}</div></section></main>;
}
